"""Public runtime API for V1 generated regression tests.

This module is the locked public surface that pytest files generated by
``tracebisect export-pytest`` import and call. Three callables plus one type
alias make up the entire surface:

- :func:`capture_trace` — run a scenario command in a subprocess and produce
  a fresh canonical trace.
- :func:`load_baseline` — read a stored ``.tbtrace`` baseline from disk.
- :func:`assert_aligned` — align baseline against candidate and raise on any
  asserted dimension that diverges.
- :data:`Trace` — type alias for the canonical trace object. Concrete type
  defined in V1; opaque at the alpha.

A generated regression test looks like::

    import subprocess
    from tracebisect.testing import (
        capture_trace,
        load_baseline,
        assert_aligned,
    )

    BASELINE_PATH = "tests/fixtures/baseline_refund_042.tbtrace"
    SCENARIO_CMD = ["python", "examples/refund_agent.py", "--case", "refund_042"]

    def test_refund_agent_no_regression():
        baseline = load_baseline(BASELINE_PATH)
        candidate = capture_trace(SCENARIO_CMD)
        assert_aligned(
            baseline=baseline,
            candidate=candidate,
            assertions=["tool_args", "final_output", "cost"],
            cost_threshold=1.5,
            mode="ci",
        )

In the alpha (0.0.1a0) all three callables raise :class:`NotImplementedError`.
The signatures are locked so generated test files written against the alpha
will continue to import and parse cleanly once V1 lands.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any, TypeAlias

__all__ = ["Trace", "assert_aligned", "capture_trace", "load_baseline"]

_REPO_URL = "https://github.com/ShebinKMohan/TraceBisect"
_ALPHA_MESSAGE = (
    "tracebisect.testing.{name} is not implemented yet "
    "(alpha 0.0.1a0). See " + _REPO_URL + " for V1 progress."
)

Trace: TypeAlias = Any
"""Canonical trace object. Concrete type defined in V1."""


def capture_trace(
    scenario_cmd: Sequence[str] | str,
    *,
    timeout_seconds: float | None = None,
    env: Mapping[str, str] | None = None,
    cwd: str | Path | None = None,
    side_effects: str = "stub",
    allow_live: bool = False,
) -> Trace:
    raise NotImplementedError(_ALPHA_MESSAGE.format(name="capture_trace"))


def load_baseline(path: str | Path) -> Trace:
    raise NotImplementedError(_ALPHA_MESSAGE.format(name="load_baseline"))


def assert_aligned(
    *,
    baseline: Trace,
    candidate: Trace,
    assertions: Sequence[str],
    cost_threshold: float = 1.5,
    mode: str = "ci",
) -> None:
    raise NotImplementedError(_ALPHA_MESSAGE.format(name="assert_aligned"))
