"""Public runtime API used by tests generated by ``tracebisect export-pytest``."""

from __future__ import annotations

import os
import shlex
import subprocess
import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Literal, TypeAlias

from tracebisect.align import align
from tracebisect.diff import Divergence, detect_divergences
from tracebisect.jsonl import read_trace
from tracebisect.schema import EventType, RunEndPayload, Trace

__all__ = ["Trace", "assert_aligned", "capture_trace", "load_baseline"]

AssertionDimension: TypeAlias = Literal[
    "tool_args",
    "final_output",
    "cost",
    "branch",
    "error_absence",
]

Mode: TypeAlias = Literal["permissive", "strict", "ci"]

_ALLOWED_ASSERTIONS = {
    "tool_args",
    "final_output",
    "cost",
    "branch",
    "error_absence",
}

_ALLOWED_MODES = {"permissive", "strict", "ci"}


def capture_trace(
    scenario_cmd: Sequence[str] | str,
    *,
    timeout_seconds: float | None = None,
    env: Mapping[str, str] | None = None,
    cwd: str | Path | None = None,
    side_effects: str = "stub",
    allow_live: bool = False,
) -> Trace:
    """Run a scenario command and read the `.tbtrace` path it writes.

    The scenario receives ``TRACEBISECT_OUTPUT`` in its environment and is
    expected to write one canonical trace there. This is the minimal V1 runtime
    contract used by generated tests and by the demo recorder.
    """
    if side_effects not in {"stub", "live"}:
        raise ValueError("side_effects must be 'stub' or 'live'")
    if side_effects == "live" and not allow_live:
        raise ValueError("side_effects='live' requires allow_live=True")

    command = shlex.split(scenario_cmd) if isinstance(scenario_cmd, str) else list(scenario_cmd)
    if not command:
        raise ValueError("scenario_cmd must not be empty")

    with tempfile.TemporaryDirectory(prefix="tracebisect-capture-") as temp_dir:
        output_path = Path(temp_dir) / "candidate.tbtrace"
        child_env = os.environ.copy()
        if env is not None:
            child_env.update(env)
        child_env["TRACEBISECT_OUTPUT"] = str(output_path)
        child_env["TRACEBISECT_SIDE_EFFECTS"] = side_effects

        subprocess.run(
            command,
            cwd=str(cwd) if cwd is not None else None,
            env=child_env,
            check=True,
            timeout=timeout_seconds,
        )
        if not output_path.exists():
            raise RuntimeError("scenario command completed but did not write TRACEBISECT_OUTPUT")
        return read_trace(output_path)


def load_baseline(path: str | Path) -> Trace:
    """Load a stored canonical baseline trace."""
    return read_trace(path)


def assert_aligned(
    *,
    baseline: Trace,
    candidate: Trace,
    assertions: Sequence[str],
    cost_threshold: float = 1.5,
    mode: Mode = "ci",
) -> None:
    """Assert selected V1 dimensions between a baseline and candidate trace."""
    if isinstance(assertions, str):
        raise TypeError("assertions must be a sequence of assertion dimension strings")
    if mode not in _ALLOWED_MODES:
        raise ValueError("mode must be one of: permissive, strict, ci")

    selected = list(assertions)
    unknown = sorted(set(selected) - _ALLOWED_ASSERTIONS)
    if unknown:
        raise ValueError(f"unsupported assertion dimension(s): {', '.join(unknown)}")

    matches = align(baseline, candidate)
    divergences = detect_divergences(matches, baseline, candidate)
    failures: list[str] = []

    if "tool_args" in selected:
        failures.extend(_format_divergences(divergences, "changed_tool_args"))
    if "branch" in selected:
        failures.extend(_format_divergences(divergences, "branch_changed"))
    if "final_output" in selected:
        baseline_output = _final_output(baseline)
        candidate_output = _final_output(candidate)
        if baseline_output != candidate_output:
            failures.append(
                f"final_output changed: expected {_display(baseline_output)}, "
                f"actual {_display(candidate_output)}"
            )
    if "cost" in selected:
        ratio = _cost_ratio(_trace_cost(candidate), _trace_cost(baseline))
        if ratio > cost_threshold:
            failures.append(
                f"cost regression: ratio {ratio:.2f}x exceeds threshold {cost_threshold:g}x"
            )
    if "error_absence" in selected:
        introduced = [
            divergence
            for divergence in divergences
            if divergence.type == "extra_event"
            and divergence.candidate_event is not None
            and divergence.candidate_event.type is EventType.ERROR
        ]
        failures.extend(f"error_absence violated: {item.description}" for item in introduced)

    if failures:
        raise AssertionError("\n".join(failures))


def _format_divergences(divergences: list[Divergence], divergence_type: str) -> list[str]:
    return [
        f"{divergence.type}: {divergence.description}"
        for divergence in divergences
        if divergence.type == divergence_type
    ]


def _final_output(trace: Trace) -> str | None:
    payload = _run_end(trace)
    if payload is None:
        return None
    return payload.final_output


def _trace_cost(trace: Trace) -> float:
    payload = _run_end(trace)
    if payload is not None:
        return payload.total_cost_usd
    return 0.0


def _run_end(trace: Trace) -> RunEndPayload | None:
    for event in reversed(trace.events):
        if isinstance(event.payload, RunEndPayload):
            return event.payload
    return None


def _cost_ratio(candidate_cost: float, baseline_cost: float) -> float:
    return candidate_cost / max(baseline_cost, 1e-12)


def _display(value: object) -> str:
    return "missing" if value is None else repr(value)
